model:
  type: "HierarchicalBoxVAE"
  config:
    embed_dim: 8
    grid_size: [4, 4]
    input_resolution: [64, 64]
    crop_padding_range: [4,8]
    beta_scale: 0.4
    beta_pre_init: 0.0
    beta_activation: sigmoid
    vae_config:
      hidden_dims: [32, 64, 128, 256]
    prior_config:
      boxes_per_level: [12, 4]
      gumbel_temp: 0.1
      gumbel_hard: False
      init_config:
        center_variance: 1.0
        width_variance: 0.3
        min_width: 0.3
        sparse_init: True
        num_init_connections: 6
        logit_value: 0.4
    pull_loss_method: corner_distance
    pull_assignment_temperature: 0.1
    pull_assignment_activation: gumbel_softmax
    pull_assignment_hard: True
    pull_loss_start_epoch: 0
    pull_loss_warmup_epochs: 5
    disjoint_loss_method: ["intersection_volume", "centroid_distance"] 
    loss_weights:
      patch_pull_loss: 10.0
      full_image_pull_loss: 0.0
      patch_mse_loss: 50.0
      patch_ssim_loss: 200.0
      full_image_mse_loss: 0.0
      full_image_ssim_loss: 0.0
      l0_entropy_loss: 0.0
      l1_entropy_loss: 0.0
      l0_vol_penalty: 0.0
      l1_vol_penalty: 0.0
      l0_disjoint_loss: 100.0
      l1_disjoint_loss: 0.0
      patch_disjoint_loss: 0.0
      full_image_disjoint_loss: 0.0

data:
  train:
    type: v0Dataset
    config:
      image_size: [64, 64]
      shapes: ["circle", "square"]
      colors: ["red"]
      num_samples: 1000
      return_metadata: True
      center_range: [16, 48]
      size_range: [10, 30]
    dataloader_config:
      batch_size: 32
      shuffle: True

trainer:
  max_epochs: 200
  optimizer:
    type: Adam
    config:
      vae_lr: 0.0001
      prior_lr: 0.0001