model:
  type: "HierarchicalBoxEmbeddingsVAE"
  config:
    embed_dim: 8
    hidden_dims: [32, 64, 128, 256]
    grid_size: [4, 4]
    input_resolution: [64, 64]
    beta_scale: 0.4
    crop_padding_range: [4,8]
    pull_method: distance
    hebbian_start_epoch: 50
    prior_config:
      boxes_per_level: [32, 4]
      gumbel_temp: 0.5
      gumbel_hard: False
      init_config:
        sparse_init: True
        num_init_connections: 10
        logit_value: 0.2
    loss_weights:
      patch_pull_loss: 1.0
      full_image_pull_loss: 1.0
      inclusion_loss: 1.0
      exclusion_loss: 0.0
      patch_mse_loss: 10.0
      patch_ssim_loss: 2.0
      full_image_mse_loss: 10.0
      full_image_ssim_loss: 2.0
      loss_uniform_patch: 0.0
      loss_uniform_full: 0.0
      loss_disjoint_full: 0.0
      entropy_loss: 0.0
      hebbian_loss: 1.0
      l0_entropy_loss: 0.0
      l1_entropy_loss: 0.0
      l0_vol_penalty: 0.0

data:
  train:
    type: v0Dataset
    config:
      image_size: [64, 64]
      shapes: ["circle", "square"]
      colors: ["red"]
      num_samples: 1000
      return_metadata: True
      center_range: [16, 48]
      size_range: [10, 30]
    dataloader_config:
      batch_size: 32
      shuffle: True

trainer:
  max_epochs: 200
  optimizer:
    type: Adam
    config:
      vae_lr: 0.0001
      prior_lr: 0.01